-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 15:31:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Classificado-t2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Classificado-t2` ;

-- -----------------------------------------------------
-- Schema Classificado-t2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Classificado-t2` DEFAULT CHARACTER SET latin1 ;
USE `Classificado-t2` ;

-- -----------------------------------------------------
-- Table `Classificado-t2`.`CodPostal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classificado-t2`.`CodPostal` ;

CREATE TABLE IF NOT EXISTS `Classificado-t2`.`CodPostal` (
  `idCodPostal` INT NOT NULL AUTO_INCREMENT,
  `localidade` VARCHAR(45) NOT NULL,
  `codpostal` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idCodPostal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classificado-t2`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classificado-t2`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Classificado-t2`.`Clientes` (
  `idClientes` INT NOT NULL,
  `nome` VARCHAR(15) NULL,
  `apelido` VARCHAR(30) NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(9) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nif` VARCHAR(9) NULL,
  `idCodPostal` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_CodPostal1_idx` (`idCodPostal` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_CodPostal1`
    FOREIGN KEY (`idCodPostal`)
    REFERENCES `Classificado-t2`.`CodPostal` (`idCodPostal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classificado-t2`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classificado-t2`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `Classificado-t2`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classificado-t2`.`Anuncios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classificado-t2`.`Anuncios` ;

CREATE TABLE IF NOT EXISTS `Classificado-t2`.`Anuncios` (
  `idAnuncios` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `mensagem` VARCHAR(45) NULL,
  `datainicio` DATE NULL,
  `datafim` DATE NULL,
  `datasubmissao` DATE NULL,
  `idClientes` INT NOT NULL,
  `idCategorias` INT NOT NULL,
  PRIMARY KEY (`idAnuncios`),
  INDEX `fk_Anuncios_Clientes_idx` (`idClientes` ASC) VISIBLE,
  INDEX `fk_Anuncios_Categorias1_idx` (`idCategorias` ASC) VISIBLE,
  CONSTRAINT `fk_Anuncios_Clientes`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Classificado-t2`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anuncios_Categorias1`
    FOREIGN KEY (`idCategorias`)
    REFERENCES `Classificado-t2`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classificado-t2`.`TipoPagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classificado-t2`.`TipoPagamento` ;

CREATE TABLE IF NOT EXISTS `Classificado-t2`.`TipoPagamento` (
  `idTipoPagamento` INT NOT NULL AUTO_INCREMENT,
  `descricaopagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classificado-t2`.`Fatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classificado-t2`.`Fatura` ;

CREATE TABLE IF NOT EXISTS `Classificado-t2`.`Fatura` (
  `idFatura` INT NOT NULL AUTO_INCREMENT,
  `datafatura` DATE NULL,
  `totalfatura` DOUBLE NULL,
  `idTipoPagamento` INT NOT NULL,
  PRIMARY KEY (`idFatura`),
  INDEX `fk_Fatura_TipoPagamento1_idx` (`idTipoPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Fatura_TipoPagamento1`
    FOREIGN KEY (`idTipoPagamento`)
    REFERENCES `Classificado-t2`.`TipoPagamento` (`idTipoPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classificado-t2`.`DetalheFatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classificado-t2`.`DetalheFatura` ;

CREATE TABLE IF NOT EXISTS `Classificado-t2`.`DetalheFatura` (
  `idAnuncios` INT NOT NULL,
  `idFatura` INT NOT NULL,
  `subTotal` FLOAT NULL,
  PRIMARY KEY (`idAnuncios`, `idFatura`),
  INDEX `fk_Anuncios_has_Fatura_Fatura1_idx` (`idFatura` ASC) VISIBLE,
  INDEX `fk_Anuncios_has_Fatura_Anuncios1_idx` (`idAnuncios` ASC) VISIBLE,
  CONSTRAINT `fk_Anuncios_has_Fatura_Anuncios1`
    FOREIGN KEY (`idAnuncios`)
    REFERENCES `Classificado-t2`.`Anuncios` (`idAnuncios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anuncios_has_Fatura_Fatura1`
    FOREIGN KEY (`idFatura`)
    REFERENCES `Classificado-t2`.`Fatura` (`idFatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Classificado-t2`.`CodPostal`
-- -----------------------------------------------------
START TRANSACTION;
USE `Classificado-t2`;
INSERT INTO `Classificado-t2`.`CodPostal` (`idCodPostal`, `localidade`, `codpostal`) VALUES (DEFAULT, 'Barreiro', '2830132');
INSERT INTO `Classificado-t2`.`CodPostal` (`idCodPostal`, `localidade`, `codpostal`) VALUES (DEFAULT, 'Barreiro', '2830034');
INSERT INTO `Classificado-t2`.`CodPostal` (`idCodPostal`, `localidade`, `codpostal`) VALUES (DEFAULT, 'Baixa da Banheira', '2835445');
INSERT INTO `Classificado-t2`.`CodPostal` (`idCodPostal`, `localidade`, `codpostal`) VALUES (DEFAULT, 'Moita', '2860001');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Classificado-t2`.`Categorias`
-- -----------------------------------------------------
START TRANSACTION;
USE `Classificado-t2`;
INSERT INTO `Classificado-t2`.`Categorias` (`idCategorias`, `nome`) VALUES (DEFAULT, 'Tecnologia');
INSERT INTO `Classificado-t2`.`Categorias` (`idCategorias`, `nome`) VALUES (DEFAULT, 'Desporto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Classificado-t2`.`TipoPagamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `Classificado-t2`;
INSERT INTO `Classificado-t2`.`TipoPagamento` (`idTipoPagamento`, `descricaopagamento`) VALUES (DEFAULT, 'Dinheiro');
INSERT INTO `Classificado-t2`.`TipoPagamento` (`idTipoPagamento`, `descricaopagamento`) VALUES (DEFAULT, 'Cartao_credito');
INSERT INTO `Classificado-t2`.`TipoPagamento` (`idTipoPagamento`, `descricaopagamento`) VALUES (DEFAULT, 'Cheque');

COMMIT;

