-- MySQL Script generated by MySQL Workbench
-- Mon May 11 16:22:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_db` DEFAULT CHARACTER SET utf8 ;
USE `loja_db` ;

-- -----------------------------------------------------
-- Table `loja_db`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_db`.`Cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `nif` INT NOT NULL,
  `morada` VARCHAR(45) NOT NULL,
  `tlm` INT NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_db`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_db`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `quantidade` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_db`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_db`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tlm` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_db`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_db`.`Compra` (
  `idcliente` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `idcompra` INT NOT NULL,
  `idfuncionario` INT NOT NULL,
  `tipo_pagamento` VARCHAR(45) NOT NULL,
  `valor_carrinho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`, `idproduto`, `idcompra`, `idfuncionario`),
  INDEX `fk_Cliente_has_produto_produto1_idx` (`idproduto` ASC),
  INDEX `fk_Cliente_has_produto_Cliente_idx` (`idcliente` ASC),
  INDEX `fk_Compra_funcionario1_idx` (`idfuncionario` ASC),
  CONSTRAINT `fk_Cliente_has_produto_Cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `loja_db`.`Cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_produto_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `loja_db`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_funcionario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `loja_db`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
